const doctorSpecialties = [
    'Dentist', 
    'Gynecologist/Obstetrician', 
    'General Physician', 
    'Dermatologist', 
    'Ear-Nose-Throat (ENT) Specialist', 
    'Homeopath', 
    'Ayurveda', 
    'Cardiologist', 
    'Neurologist', 
    'Orthopedic Surgeon', 
    'Pediatrician', 
    'Psychiatrist', 
    'Oncologist', 
    'Pulmonologist', 
    'Nephrologist', 
    'Urologist', 
    'Endocrinologist', 
    'Gastroenterologist', 
    'Rheumatologist', 
    'Ophthalmologist', 
    'Anesthesiologist', 
    'Allergist/Immunologist', 
    'Hematologist', 
    'Infectious Disease Specialist', 
    'Plastic Surgeon', 
    'Radiologist', 
    'Emergency Medicine Specialist', 
    'Nuclear Medicine Specialist', 
    'Geriatrician', 
    'Pathologist', 
    'Podiatrist', 
    'Sports Medicine Specialist', 
    'Osteopath', 
    'Chiropractor'
];

export default doctorSpecialties;